### ISSUE TITLE
ERROR while running DeepOCR in Jupyter. Please help me with the issue, sir.

### ISSUE THREAD

**Issue by balajiich** [nicholastoddsmith/pythonml#10]
INFO:tensorflow:Restoring parameters from TFModel/ocrgraph
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-3728b4fff9df> in <module>()
    146     PA = P.parse_args()
    147     if PA.f:
--> 148         FitModel()
    149     for img in PA.Img:
    150         I = imread(img)[:, :, :3]    #Read image and discard alpha

TypeError: FitModel() missing 5 required positional arguments: 'cnnc', 'A', 'Y', 'T', and 'FN'

![untitled](https://user-images.githubusercontent.com/19875378/37878258-ab962fa0-3083-11e8-9187-1520a7f1c6d1.png)

**Comment by nicholastoddsmith** [comment]
Based on the past 2 issues you raised, this looks like a problem with your installation.
