### ISSUE TITLE
self.TFVar = set(tf.global_variables()) ----> module 'tensorflow' has no attribute 'global_variables'

### ISSUE THREAD

**Issue by adradr** [nicholastoddsmith/pythonml#2]
> `---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-26-b2e782dd3bd1> in <module>()
>      18       ('C1d', [8, NC * 2, NC], 4)]
>      19 #Create the neural network in TensorFlow
> ---> 20 cnnc = ANNR(B[0].shape, ns, batchSize = 32, learnRate = 2e-5, maxIter = 5, reg = 1e-5, tol = 1e-2, verbose = True)
>      21 
>      22 cnnc.fit(B, Y)
> 
> <ipython-input-18-f2b3807b301a> in __init__(self, _IS, _NA, batchSize, learnRate, loss, maxIter, name, optmzrn, pad, reg, tol, verbose, X, Y)
>     210         self.TFVar = None
>     211         with tf.variable_scope(self.name):
> --> 212             self.TFVar = set(tf.global_variables())                 #All variables before model
>     213             self.CreateModel()                                      #Populate TensorFlow graph
>     214             self.TFVar = set(tf.global_variables()) - self.TFVar    #Only variables in this model
> 
> AttributeError: module 'tensorflow' has no attribute 'global_variables'
> `

hello! im trying to run the following command based on your crypto tutorial but it says no global var...

any ideas?

**Comment by nicholastoddsmith** [comment]
Hi,

Which version of tensorflow are you using? It sounds like there is something wrong with your tensorflow installation or you might be using an older version.

N

**Comment by adradr** [comment]
im using tf installed with anaconda. TF version 0.11.0rc0

**Comment by nicholastoddsmith** [comment]
Looking through the API documentation for r0.12, you will see that _global_variables_ is missing. It seems the _global_variables_ function wasn't introduce till around r1.0. You'll need to upgrade your tensorflow version to use the class. Closing as this isn't an issue with my code.

N

**Comment by adradr** [comment]
thanks!
