### ISSUE TITLE
some error informations ask you...

### ISSUE THREAD

**Issue by wenyu332** [nicholastoddsmith/pythonml#3]
In DeepOCR ,I used your code in blog MakeImg.py  generated pictures and train.csv.Then I wanted to use DeepOCR.py to train ocrnet.model . However,there had some questions about “ValueError: Cannot feed value of shape (64, 32, 640, 3) for Tensor 'tfann/Placeholder:0', which has shape '(?, 14, 640, 3)' ” I queried some answers like this [https://stackoverflow.com/questions/37433321/tensorflow-tflearn-valueerror-cannot-feed-value-of-shape-64-for-tensor-uta](url).But I don't understand how to solved it.So if you give me some suggestions,I would be very grateful.  Thanks for your reading.

**Comment by nicholastoddsmith** [comment]
The sizes of your image files don't match up. It looks like your training images are 14 pixels high but your testing images are 32 pixels high. In the future, please ask programming related question on StackOverflow (feel free to tag me @nickandross). Thanks!

N
