### ISSUE TITLE
ERROR while running DeepOCR in spyder :( , please help me out, sir

### ISSUE THREAD

**Issue by balajiich** [nicholastoddsmith/pythonml#9]
![untitled](https://user-images.githubusercontent.com/19875378/37878135-c5d1a13a-3081-11e8-8201-a87ab73110c3.png)

Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

runfile('D:/nicholastsmith/DeepOCR.py', wdir='D:/nicholastsmith')
INFO:tensorflow:Restoring parameters from TFModel/ocrgraph
usage: DeepOCR.py [-h] [-f] I [I ...]
DeepOCR.py: error: the following arguments are required: I
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\chegu\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by nicholastoddsmith** [comment]
Do not file issues to troubleshoot you code/installation problems.
